name: "CD: executor (prod)"

on:
  push:
    branches:
      - 'deploy-executor-prod'

env:
  TAG_VERSION: "v0-latest"
  STAGING_DOCKER_REPO_NAME: "backenddevelopersltd/compute-horde-executor-staging"
  DOCKER_REPO_NAME: "backenddevelopersltd/compute-horde-executor"
  DIST_VERSION_PREFIX: "executor-prod"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker build and push
        run: |
          docker run -d --name my-redis -p 6379:6379 redis
            
  tagging:
    needs: deploy
    uses: ./.github/workflows/common_tagging.yml
    with:
      DIST_VERSION_PREFIX: "executor-prod"
